version: '3.9'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kea-db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: Project
      MYSQL_ROOT_PASSWORD: toor
    restart: always
  app:
    build: .
    ports:
      - "5000:5000"
    restart: always
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - app
    environment:
      SERVER_URL: http://app:5000
      STAGE: all

volumes:
  kea-db_data:
